# Blinker Makefile
# written by: Craig A. Lindley
# last update: 02/21/99

JAVA_FILES = \
	Blinker.java \
	
include ..\..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


