# Compressor/Expander Makefile
# written by: Craig A. Lindley
# last update: 09/27/98

JAVA_FILES = \
	GraphSurface.java \
	LabeledGraphSurface.java \

include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


