# Button Package Makefile
# written by: Craig A. Lindley
# last update: 03/13/99

JAVA_FILES = \
	Button.java \
	ButtonTypeDisplay.java \
	RoundButton.java \
	RoundButtonBeanInfo.java \
	SquareButton.java \
	SquareButtonBeanInfo.java \
	ToggleSwitchButton.java \
	ToggleSwitchButtonBeanInfo.java \

	
include ..\..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


