# JMF2.0 Devices Makefile
# written by: Craig A. Lindley
# last update: 06/09/99

JAVA_FILES = \
	JMFFileBase.java \
	JMFFileCallBackIF.java \
	JMFFileUI.java \
	JMFFileWithUI.java \
	JMFFileWriterUI.java \
	JMFFileWriterWithUI.java \
	JMFMicUI.java \
	JMFMicWithUI.java \
	JMFPlayerUI.java \
	JMFPlayerWithUI.java \

include ..\..\..\Makefile.rules

all:	$(CLASSFILES)
	@echo done

clobber:
	rm -f *.class 


