# Simulated Front Panel Package Makefile
# written by: Craig A. Lindley
# last update: 04/04/99

JAVA_FILES = \
	CompressorFrontPanel.java \
	DemoFrontPanel.java \
	EQFrontPanel.java \
	StereoVUMetersFrontPanel.java \
	
include ..\Makefile.rules

all:	$(CLASSFILES)
	@echo done

clobber:
	rm -f *.class 


