# Spectrum Analyzer Makefile
# written by: Craig A. Lindley
# last update: 02/27/99

JAVA_FILES = \
	FFT.java \
	SpectrumAnalyzer.java \
	SpectrumAnalyzerUI.java \
	StatusDisplay.java \


include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


