# Phrase Sampler Application Makefile
# written by: Craig A. Lindley
# last update: 02/13/99

JAVA_FILES = \
	RiffOMatic.java \
	RiffOMaticUI.java \

include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


