# Pots Package Makefile
# written by: Craig A. Lindley
# last update: 03/18/99

JAVA_FILES = \
	BoostCutSlidePot.java \
	IntValuedPot.java \
	IntValuedSlidePot.java \
	Pot.java \
	PotBase.java \
	PotBeanInfo.java \
	PotTypeDemo.java \
	RealValuedPot.java \
	RealValuedSlidePot.java \
	SlidePot.java \
	SlidePotBeanInfo.java \

include ..\..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


