# Processors Package Makefile
# written by: Craig A. Lindley
# last update: 04/18/99

JAVA_FILES = \
	AmplitudeAdjustUI.java \
	AmplitudeAdjustWithUI.java \
	Cache.java \
	ChorusUI.java \
	ChorusWithUI.java \
	CompExpUI.java \
	CompExpWithUI.java \
	DelayUI.java \
	DelayWithUI.java \
	DistortionUI.java \
	DistortionWithUI.java \
	GraphicEQUI.java \
	GraphicEQWithUI.java \
	PannerUI.java \
	PannerWithUI.java \
	ParametricEQUI.java \
	ParametricEQWithUI.java \
	PhaserUI.java \
	PhaserWithUI.java \
	PitchShifterUI.java \
	PitchShifterWithUI.java \
	ReverbUI.java \
	ReverbWithUI.java \

include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


