# JMF PCM Player Makefile
# written by: Craig A. Lindley
# last update: 08/02/98


JAVA_FILES = \
	ControllerAdapter.java \
	PCMDataSource.java \
	PCMSourceStream.java \
	_PCMPlayer.java \
	PCMPlayer.java \
	PCMPlayerWithUI.java \
	
include ..\..\Makefile.rules

all:	$(CLASSFILES)
	@echo done

clobber:
	rm -f *.class 


