# Meters Package Makefile
# written by: Craig A. Lindley
# last update: 03/26/99

JAVA_FILES = \
	AnalogMeter.java \
	LEDMeter.java \
	Meter.java \
	MeterDemo.java \
	RoundLEDMeter.java \

include ..\..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


