# Chromatic Tuner Application Makefile
# written by: Craig A. Lindley
# last update: 04/01/99

JAVA_FILES = \
	ComputeFrequencyWithFFT.java \
	Tuner.java \
	TunerUI.java \

include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


