# WaveRead Makefile
# written by: Craig A. Lindley
# last update: 09/02/98

JAVA_FILES = \
	WaveRead.java \
	WaveWrite.java \
	WaveWriteDevice.java \
	
include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


