# Reverb Components Subdirectory Makefile
# written by: Craig A. Lindley
# last update: 09/07/98

JAVA_FILES = \
	AllpassNetwork.java \
	CombFilter.java \
	SchroederReverb.java \


include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


