# Leds Package Makefile
# written by: Craig A. Lindley
# last update: 04/01/99

JAVA_FILES = \
	LabeledLED.java \
	LEDBase.java \
	LEDTypeDemo.java \
	RoundLED.java \
	SquareLED.java \

include ..\..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


