# Oscillator Package Makefile
# written by: Craig A. Lindley
# last update: 08/22/98

JAVA_FILES = \
	Oscillator.java \
	OscillatorWithUI.java \
	StereoOscillator.java \
	StereoOscillatorWithUI.java \

	
include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


