# Audio Test Makefile
# written by: Craig A. Lindley
# last update: 10/01/98

JAVA_FILES = \
	AudioTest.java
	
include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


