# AU File Makefile
# written by: Craig A. Lindley
# last update: 08/04/98

JAVA_FILES = \
	AURead.java \
	AUWrite.java \
	AUWriteDevice.java \
	
include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


