# Scope Makefile
# written by: Craig A. Lindley
# last update: 02/25/99

JAVA_FILES = \
	TriggerFlag.java \
	Scope.java \
	ScopeUI.java \
	StatusDisplay.java \

include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


