# jmf20 packages makefile
# written by: Craig A. Lindley
# last update: 06/05/99

SUBDIRS	= \

JAVA_FILES = \
	DataSource.java \

include ..\..\..\..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 
