# WinPlayer Makefile
# written by: Craig A. Lindley
# last update: 12/06/98

JAVA_FILES = \
	WinPlayer.java \
	WinPlayerWithUI.java \
	
include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


