/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WinPlayer */

#ifndef _Included_WinPlayer
#define _Included_WinPlayer
#ifdef __cplusplus
extern "C" {
#endif
#undef WinPlayer_ALLTYPES
#define WinPlayer_ALLTYPES -1L
#undef WinPlayer_NOTYPE
#define WinPlayer_NOTYPE 0L
#undef WinPlayer_SOURCE
#define WinPlayer_SOURCE 1L
#undef WinPlayer_PROCESSOR
#define WinPlayer_PROCESSOR 2L
#undef WinPlayer_MONITOR
#define WinPlayer_MONITOR 3L
#undef WinPlayer_SINK
#define WinPlayer_SINK 4L
#undef WinPlayer_MINSAMPLERATE
#define WinPlayer_MINSAMPLERATE 8000L
#undef WinPlayer_MAXSAMPLERATE
#define WinPlayer_MAXSAMPLERATE 44100L
#undef WinPlayer_DEFAULTSAMPLERATE
#define WinPlayer_DEFAULTSAMPLERATE 11025L
/* Inaccessible static: buffer */
/* Inaccessible static: initComplete */
/* Inaccessible static: resetMode */
/*
 * Class:     WinPlayer
 * Method:    nativeSelectDevice
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_WinPlayer_nativeSelectDevice
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     WinPlayer
 * Method:    nativePlay
 * Signature: (Lcraigl/winplayer/WinPlayer;)V
 */
JNIEXPORT void JNICALL Java_WinPlayer_nativePlay
  (JNIEnv *, jclass, jobject);

/*
 * Class:     WinPlayer
 * Method:    nativeReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WinPlayer_nativeReset
  (JNIEnv *, jclass);

/*
 * Class:     WinPlayer
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WinPlayer_nativeClose
  (JNIEnv *, jclass);

/*
 * Class:     WinPlayer
 * Method:    nativeStoreSamples
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_WinPlayer_nativeStoreSamples
  (JNIEnv *, jclass, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
