/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class craigl_winrecorder_WinRecorder */

#ifndef _Included_craigl_winrecorder_WinRecorder
#define _Included_craigl_winrecorder_WinRecorder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     craigl_winrecorder_WinRecorder
 * Method:    nativeHasSoundCard
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_craigl_winrecorder_WinRecorder_nativeHasSoundCard
  (JNIEnv *, jobject);

/*
 * Class:     craigl_winrecorder_WinRecorder
 * Method:    nativeInitRecorder
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_craigl_winrecorder_WinRecorder_nativeInitRecorder
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     craigl_winrecorder_WinRecorder
 * Method:    nativeResetRecorder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_craigl_winrecorder_WinRecorder_nativeResetRecorder
  (JNIEnv *, jobject);

/*
 * Class:     craigl_winrecorder_WinRecorder
 * Method:    nativeCloseRecorder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_craigl_winrecorder_WinRecorder_nativeCloseRecorder
  (JNIEnv *, jobject);

/*
 * Class:     craigl_winrecorder_WinRecorder
 * Method:    nativeGetSamples
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_craigl_winrecorder_WinRecorder_nativeGetSamples
  (JNIEnv *, jobject, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
