# WinRecorder Makefile
# written by: Craig A. Lindley
# last update: 08/01/98

JAVA_FILES = \
	RecorderIF.java \
	WinRecorder.java \
	WinRecorderWithUI.java \
	
include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


