# UI Utils Package Makefile
# written by: Craig A. Lindley
# last update: 03/21/99

JAVA_FILES = \
	BaseUI.java \
	Border.java \
	Box.java \
	CloseableFrame.java \
	CloseableFrameIF.java \
	DrawnRectangle.java \
	EtchedBorder.java \
	EtchedRectangle.java \
	Etching.java \
	MessageBox.java \
	Orientation.java \

include ..\..\Makefile.rules

CLASSES	= \
	$(JAVA_FILES:.java=.class)

all:	$(CLASSES)
	@echo done

clobber:
	rm -f *.class 


